// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackBtn: typeof import('./../src/components/BackBtn.vue')['default']
    Breadcrumb: typeof import('./../src/components/Breadcrumb.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    GithubCorner: typeof import('./../src/components/GithubCorner.vue')['default']
    Index: typeof import('./../src/components/Captcha/Index.vue')['default']
    Pagination: typeof import('./../src/components/Pagination.vue')['default']
    PanThumb: typeof import('./../src/components/PanThumb.vue')['default']
    RightPanel: typeof import('./../src/components/RightPanel.vue')['default']
    ScreenFull: typeof import('./../src/components/ScreenFull.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon.vue')['default']
  }
}

export { }
