name: "Frontend"
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run Tests and check code format
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-web-node14-${{ hashFiles('apps/web/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-web-node14-
    - name: Install dependencies and deploy staging
      if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || (github.event_name == 'deployment' && github.event.deployment.environment == 'staging')
      env:
        AWS_DEFAULT_REGION: us-west-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        npm install -g @vue/cli@4.5.13
        npm install
        npm run build:mock
        aws s3 sync --delete dist/ s3://logistics.vibe.dev/
        aws cloudfront create-invalidation \
            --distribution-id E1QRAWF4RAJF91 \
            --paths "/*"
    - name: Install dependencies and deploy production
      if: github.event_name == 'deployment' && github.event.deployment.environment == 'production' && github.ref == 'refs/heads/master'
      env:
        AWS_DEFAULT_REGION: us-west-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        npm install -g @vue/cli@4.5.13
        npm install
        npm run build:prod
        aws s3 sync --delete dist/ s3://logistics.vibe.dev/
        aws cloudfront create-invalidation \
            --distribution-id E1QRAWF4RAJF91 \
            --paths "/*"
